export const LABELS = {
  LINE: 'Line',
  ALTERNATE_SEQ_NUM: 'Alternate Sequence Number',
  TFC_UCID: 'Unique Claim ID',
  TFC_SUBMISSION_TYPE: 'TFC Submission Type',
  TFC_FULL_OVERRIDE_REASON: 'Full Override Reason',
  TFC_APPLICATION_TYPE: 'TFC Application Type',
  TFC_ADULT_ROLE: 'TFC Adult Role',
  NATIONALITY: 'Nationality',
  COUNTRY_OF_RESIDENCE: 'Country of Residence',
  CHECKBOX_LABEL: 'checkbox label',
  COUNTRY: 'Country',
  DESCRIPTION: 'Description',
  FORENAME: 'Forename',
  GENDER: 'Gender',
  EFE_VOUCHER_CODE: 'EFE Voucher Code',
  MARRIAGE_CP_STATUS: 'Marriage/CP Status',
  MERGE_STATUS: 'Merge Status',
  NINO: 'NINO',
  RESPONSE_TOP_UP_NUMBER: 'Response Top-Up Number',
  RESPONSE_TOP_UP_RATE: 'Response Top-Up Rate',
  SPECIALIST_BUSINESS_AREA: 'Specialist Business Area',
  SURNAME: 'Surname',
  TITLE: 'Title',
  CRN: 'Child Reference Number',
  END_DATE: 'End Date',
  ELIGIBILITY_CODE: 'eligibility-code',
  ELIGIBILITY_RESPONSE: 'eligibility-response',
  NSI_CHILD_ID: 'nsi-child-id',
  RESPONSE_NARATIVE: 'response-narative',
  TFC_DECLARATION_ID: 'tfc-declaration-id',
  WI_STATUS: 'Work Item Status',
  BF_DATE: 'Brought Forward Date',
  OTHER_DISPLAY_DATA: 'Other Display Data',
  TFC_EP_TOP_UP_RATE: 'TFC EP Top Up Rate',
  TFC_EP_MAX_TOP_UP_AMOUNT: 'TFC EP Max Top Up Amount',
  CERTIFIED_BLIND: 'Certified Blind',
  AFIP: 'AFIP',
  LATEST_RESPONSE: 'Latest Response',
  TFC_TOP_UP_RATE: 'TFC Top Up Rate',
  BRN: 'BRN',
  MIDDLENAME: 'Middlename(s)',
  TFC_OVERRIDE_REASON: 'Override Reason',
  EFE_CODE: 'EFE Code',
  RELATIONSHIP: 'Relationship',
  RELATIONSHIP_TYPE: 'Relationship Type',
  RELATIONSHIP_WITH_CHILD: 'Relationship With Child',
  SL_DROPDOWN: 'Dropdown',
  SL_DESCRPTION: 'Description',
  START_DATE: 'Start Date',
  DATE: 'Date',
  TFC_SUBJECT: 'Subject',
  TFC_MESSAGE_DETAILS: 'Message Details',
  ERROR_MESSAGE: 'No records found',
  TAX_YEAR: 'Tax Year',
  TFC_CHILD_UNIQUE_CLAIM_INDENTIFIER: 'Child UCI',
  DATE_OF_BIRTH: 'Date Of Birth',
  INSTITUTION_TYPE: 'Institution Type',
  INSTITUTION_NAME: 'Institution Name',
  NATIONALITY_GROUP: 'Nationality Group',
  CITY: 'City',
  EMAIL: 'Email Address',
  PHONE_NUMBER: 'Phone Number',
  CHILDCARE_VOUCHER: 'Childcare Vouchers',
  POSTCODE: 'Postcode',
  BANKRUPTCY_FILED_DATE: 'Bankruptcy Filed Date',
  SPECIAL_BUSINESS_AREA: 'Special Business Area',
  SA_START_YEAR: 'SA Start Year',
  SA_FINAL_YEAR: 'SA Final Year',
  REASON: 'Reason',
  OTHER_REASON: 'Other Reason',
  ADDITIONAL_NOTES: 'Additional Notes',
  ACCOUNT_STATUS: 'Account Status',
  IMMIGRATION_CASE_VALID_UNTILL: 'Immigration Case Valid Untill',
  STARTUP_PERIOD_DATE: 'Startup Period Date',
  MONEY: 'Money',
  END_REASON: 'End Reason',
  START_REASON: 'Start Reason',
  DOCUMENT_TYPE: 'Document Type',
  CONTACT_CHANNEL: 'Contact Channel',
  CONTACT_DIRECTION: 'Contact Direction',
  CONTACTOR_TYPE: 'Contactor Type',
  CONTACT_STORAGE_REF: 'Contact Storage Reference',
  OPERATOR_ID: 'Operator ID',
  CONTACTOR_REF: 'Contactor Reference',
  ACTIONS: 'Actions',
  CONTACT_TYPE: 'Contact Type',
  TIME_OF_CONTACT: 'Time of Contact',
  DATE_OF_CONTACT: 'Date of Contact',
  DOCUMENT_TYPE_DATE: 'Document Type Date',
  LINK: 'Link',
  LINE1: 'Line 1',
  LINE2: 'Line 2',
  LINE3: 'Line 3',
  LINE4: 'Line 4',
  LINE5: 'Line 5',
  PAYDAY: 'Payday',
  PAYMENT_FREQUENCY: 'Payment Frequency',
  ASSCONINO: 'Associated NINO',
  BLACKLIST_TYPE: 'Blacklist Type',
  BLACKLIST_SEVERITY: 'Severity Level',
  NSI_INSTRUCTION: 'NS&I Instruction',
  ASSOCIATEDINDIVIDUAL: 'Associated Individual',
  UTR: 'UTR',
  TRN: 'TRN',
  SLCREF: 'SLCREF',
  FORENAMES: 'Forename(s)',
  ADDRESS_TYPE: 'Address Type',
  HOUSE_NAME: 'House Name or Number',
  ADDRESS_DETAILS: 'Address Details',
  ADDRESSS_RLS :'Address RLS'
};
